name: Lint and Spell Check

on:
  pull_request:
    branches:
      - main

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v14
        with:
          globs: "**/*.md"

  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Spell Check
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: "**/*.md"
          config: .cspell.json